### ISSUE TITLE
Got an error when submitting data through a form

### ISSUE THREAD

**Issue by spassaro80** [lpomfrey/django-taggit-machinetags#3]
Good morning

I've set up a model with 3 different TaggableManager, one of which is Machine Taggable Manager:

`class Building(models.Model):`

  `  name = models.CharField(null=True, blank=True, max_length=50, verbose_name="Nome")`

`   #restof fields`

   ` facilities = TaggableManager(verbose_name="Impianti", blank=True)`

  `  equipments = TaggableManager(verbose_name="Dotazioni", through=Equipment, related_name="Equipments", blank=True)`

`    tot_rooms = MachineTaggableManager(verbose_name="Vani",blank=True)`

everything works fine in the shell (i can add tag machines with the api you provided". But when I try to submit data through a form, the other 2 fields works perfectly while the MachineTags raise an error: 

**"add() got an unexpected keyword argument 'through_defaults', "**

In the form I'm submitting values as value pairs like so: "somekey:somevalue".

¿could you please confirm if this is a bug or if machine tags is not meant to work with forms?

Thank you in advance!

Stefano

**Comment by lpomfrey** [comment]
What versions of django, django-taggit, and django-taggit-machinetags are you using?

**Comment by spassaro80** [comment]
Hello, thank you for the answer: 

django-taggit==1.4.0
django-taggit-machinetags==0.8.1
Django==3.1.7

**Comment by lpomfrey** [comment]
Have just released version 0.9.0 which should fix this. Re-open this issue if you have any problems.

**Comment by spassaro80** [comment]
Hello, now it's giving me another error: 

The first value is saved (with a ":" added as initial character like so:

Value inputted in form: "Property:Value"
Value saved in form: ":Property:Value"

But if i try to input another value in form (i've tried with several combinations) it always raises a Unique Constraint error:

Unique constraint failed
taggit_machinetags_machineslug

Thank you in advance!
